version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: First Step
          command: |
            echo 'Hello shit'
            echo 'Suomi finland perkele'
      - run:
          name: Code Has Arrived
          command: |
            ls -al
            echo '^^^That should look familiar^^^'
      - run:
          name: Running in a Unique Container
          command: |
            node index.js
